name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Go 1.23.12
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.12'

      - name: Build
        run: |
          mkdir -p build
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then EXT=".exe"; fi
          echo "🏗️ Building ${{ matrix.goos }}/${{ matrix.goarch }}..."
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}$EXT .

      - name: Package
        run: |
          cd build
          for f in *; do
            if [[ "$f" == *.exe ]]; then
              zip "${f%.exe}.zip" "$f"
            else
              tar -czf "$f.tar.gz" "$f"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: build

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
